name: Create Issue from Jira
on:
  repository_dispatch:
    types: [jira-issue]

permissions:
  issues: write
  contents: read

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Convert escaped newlines and create issue body
        run: |
          desc="${{ github.event.client_payload.description }}"
          todo="${{ github.event.client_payload.todo }}"

          desc=$(echo "$desc" | sed 's/\\\\n/\n/g')
          todo=$(echo "$todo" | sed 's/\\\\n/\n/g')

          cat > issue-body.md <<EOF
          ## 🚀 Description
          > $desc

          ---

          ### ✅ To-Do List
          $(echo "$todo" | sed 's/^/- [ ] /')

          ---

          ### 👤 담당자
          ${{ github.event.client_payload.reporter }}

          ### 🔗 Jira Link
          [**${{ github.event.client_payload.key }}**](${{ github.event.client_payload.url }})
          EOF

      - name: Create issue from generated file
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "[${{ github.event.client_payload.key }}] ${{ github.event.client_payload.summary }}"
          content-filepath: ./issue-body.md
          labels: |
            jira
            ${{ github.event.client_payload.type }}
